spring:
  application:
    name: pica-inspection
  zipkin:
    base-url: http://zipkin-server:9411/
server:
  port: 5005
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka